document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<title></title>");
document.writeln("<meta charset=\"utf-8\"/>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div class=\"navbar-wrapper\">");
document.writeln("	<div class=\"container\">");
document.writeln("		<nav class=\"navbar navbar-inverse navbar-static-top cl-effect-5\">");
document.writeln("			<div class=\"container\">");
document.writeln("				<div class=\"navbar-header\">");
document.writeln("					<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">");
document.writeln("						<span class=\"sr-only\">Toggle navigation</span>");
document.writeln("						<span class=\"icon-bar\"></span>");
document.writeln("						<span class=\"icon-bar\"></span>");
document.writeln("						<span class=\"icon-bar\"></span>");
document.writeln("					</button>");
document.writeln("					<a class=\"navbar-brand\" href=\"index.html\"><h1>云库课 yunkuke.cn</h1></a>");
document.writeln("				</div>");
document.writeln("				<div id=\"navbar\" class=\"navbar-collapse collapse\">");
document.writeln("					<ul class=\"nav navbar-nav navbar-right\">");
document.writeln("						<li class=\"active\"><a href=\"index.html\">首页</a></li>");
document.writeln("						<li><a href=\"about.html\">团队介绍</a><span class=\"line1\">/</span></li>");
document.writeln("						<li><a href=\"upload.html\">上传课件</a><span class=\"line1\">/</span></li>");
document.writeln("						<li><a href=\"courseware.html\">课件中心</a><span class=\"line1\">/</span></li>");
document.writeln("						<li><a href=\"login.html\">登录</a><span class=\"line1\">/</span></li>");
document.writeln("						<li><a href=\"register.html\">注册</a><span class=\"line1\">/</span></li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</nav>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("<section class=\"innerpage-banner\">");
document.writeln("</section>");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");